const genres = {
    'Action': 1,
    'Adventure': 2,
    'Avant Garde': 5,
    'Award Winning': 46,
    'Boys Love': 28,
    'Comedy': 4,
    'Drama': 8,
    'Fantasy': 10,
    'Girls Love': 26,
    'Gourmet': 47,
    'Horror': 14,
    'Mystery': 7,
    'Romance': 22,
    'Sci-Fi': 24,
    'Slice of Life': 36,
    'Sports': 30,
    'Supernatural': 37,
    'Suspense': 41,
    'Ecchi': 9,
    'Erotica': 49,
    'Hentai': 12,
    'Adult Cast': 50,
    'Anthropomorphic': 51,
    'CGDCT': 52,
    'Childcare': 53,
    'Combat Sports': 54,
    'Crossdressing': 81,
    'Delinquents': 55,
    'Detective': 39,
    'Educational': 56,
    'Gag Humor': 57,
    'Gore': 58,
    'Harem': 35,
    'High Stakes Game': 59,
    'Historical': 13,
    'Idols (Female)': 60,
    'Idols (Male)' : 61,
    'Isekai': 62,
}